env:
  es6: true
  node: true
  jest: true
extends:
  - airbnb-base
  - 'plugin:jest/recommended'
plugins:
  - jest
  - babel
parser: babel-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: 
  jest/valid-describe: off
  no-console: off
